### ISSUE TITLE
Allow users and guests to input ingredients by scanning the barcode.

### ISSUE THREAD

**Issue by nalimaye** [Capstone-Project-Team-Dragons/ingredia#2]
Allow users and guests to input ingredients they currently have, by scanning the barcode on the product.
- [x] Display a button "Scan Your Ingredients barcode" below the Search Bar.
- [x] When a Guest/User clicks that icon, ask for the user permission, for using the cellphone's camera to scan the barcode.
- [x] After successfully scanning the barcode, add the found "Product name" to the "Ingredients List" being displayed dynamically, taking them back to SearchIngredients Screen displaying the modified "Ingredients List".

**Comment by grkohli** [comment]
Completed
