### ISSUE TITLE
App launches in a "Welcome Page"

### ISSUE THREAD

**Issue by nalimaye** [Capstone-Project-Team-Dragons/ingredia#27]
When the app launches, the "Welcome Page" is displayed.
- [ ] Displays Logo/Title and a welcome message
- [ ] Gives 2 options (Buttons): "LogIn / SignUp" or "Continue as Guest".
- [ ] If "LogIn / SignUp" gets clicked, redirect to LogIn/SignUp Screen
- [ ] If "Continue as Guest" gets clicked, redirect to SearchIngredients Screen.

**Comment by grkohli** [comment]
Completed
